### ISSUE TITLE
Why isn't this repo under the argonautproject organization?

### ISSUE THREAD

**Issue by isaacvetter** [microsoft-healthcare-madison/argo-subscription-docs#1]
https://github.com/argonautproject

Is this a Microsoft project?

**Comment by jmandel** [comment]
This content can migrate to the `argonaut` org; @GinoCanessa created it here because at the time he didn't have permissions on https://github.com/argonautproject/subscriptions.

**Comment by jmandel** [comment]
Migrated content to https://github.com/argonautproject/subscriptions -- thanks @isaacvetter .
